# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
#targets:
#  $default:
#    builders:
#      manniu_router|route_builder:
#        enabled: true
#        generate_for:
#          exclude: ['**.g.dart']
#      manniu_router|route_write_builder:
#        enabled: true
#        options: { 'write': true }
#        generate_for:
#          exclude: ['**.g.dart']

builders:
  route_write_builder:
    import: 'package:manniu_router/builder.dart'
    builder_factories: ['routeWriteBuilder']
    build_extensions: {}
    auto_apply: root_package
    build_to: source

  route_builder:
    import: 'package:manniu_router/builder.dart'
    builder_factories: ['routeBuilder']
    build_extensions: { '.dart': ['.manniu_router.g.dart'] }
    auto_apply: root_package
    runs_before: ['manniu_router|route_write_builder']
    build_to: source
