name: manniu_router
description: Manniu-routeGenerator
version: 2.0.2
author: voicewitness<voicewitness@gmail.com>
homepage: https://github.com/alibaba-flutter/annotation_route

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: any
  build: any
  build_config: '>=1.0.0'
dev_dependencies:
  build_runner: '>=2.1.5'

dependency_overrides:
  build_runner_core:
    git:
      url: git@10.241.65.201:frameworkGroup/manniu-pub/build.git
      ref: patched_build_runner_2.1.5
      path: build_runner_core/
  build:
    git:
      url: git@10.241.65.201:frameworkGroup/manniu-pub/build.git
      ref: patched_build_runner_2.1.5
      path: build/

