name: manniu_router
description: Manniu-routeGenerator
version: 1.0.2
author: voicewitness<voicewitness@gmail.com>
homepage: https://github.com/alibaba-flutter/annotation_route

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: any
  build: any
  source_gen: '>=0.8.0'
  build_config: '>=0.3.0'
dev_dependencies:
  build_runner: '>=0.9.1'
  test: any

